"""add rag metadata

Revision ID: 1cb5dcf254d5
Revises: 20cae42f7d9d
Create Date: 2026-09-18 18:20:46.445763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb5dcf254d5'
down_revision: Union[str, Sequence[str], None] = '20cae42f7d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_chunks', sa.Column('section', sa.String(length=300), nullable=True))
    op.add_column('rag_chunks', sa.Column('subsection', sa.String(length=300), nullable=True))
    op.add_column('rag_documents', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('rag_documents', sa.Column('filiere', sa.String(length=200), nullable=True))
    op.add_column('rag_documents', sa.Column('source_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_documents', 'source_url')
    op.drop_column('rag_documents', 'filiere')
    op.drop_column('rag_documents', 'category')
    op.drop_column('rag_chunks', 'subsection')
    op.drop_column('rag_chunks', 'section')
    # ### end Alembic commands ###
